# QQMusic Reader 配置文件
# 注意：这些偏移量可能随QQ音乐版本更新而失效
# 如果程序无法正常工作，请使用Cheat Engine等工具重新定位内存地址

[memory_offsets]
# 基础偏移量（相对于QQMusic.dll基地址）
song_name_offset = 0x00B6975C
song_singer_offset = 0x00B69760
song_album_offset = 0x00B69764
song_lyrics_offset = 0x0002B2C

# 歌曲信息指针链（用于查找标题）
song_name_chain = [0x0]
song_singer_chain = [0x0]
song_album_chain = [0x0]
song_lyrics_chain = [0x0]

# 字符串字段偏移量（相对于最终指针）
title_offset = 0x0

[settings]
# 更新间隔（毫秒）
update_interval_ms = 500

# 最大重试次数
max_retries = 3

# 进程名称
process_name = "QQMusic.exe"

# 模块名称  
module_name = "QQMusic.dll"

# 输出文件设置
output_txt = true
output_json = true
txt_filename = "now_playing.txt"
json_filename = "now_playing.json"

# 调试模式（输出详细的内存读取信息）
debug_mode = true

# 最大字符串长度限制（防止读取错误指针导致内存溢出）
max_string_length = 4096
